### ISSUE TITLE
Migrate to CMake

### ISSUE THREAD

**Issue by Talhada** [frno7/libpes#3]
# CMake

I would like to see this project migrated to cmake, I don't think it would take much time and CMake is becoming more and more the defacto build system for cross platform c/c++ projects.

**Comment by frno7** [comment]
Oh, there are many build systems these days... Would you care to propose a CMake variant of it, and would it include C header file dependency generation _without_ any additional downloads? Perhaps CMake and Make could coexist.

**Comment by Talhada** [comment]
CMake Will generate the makefiles for tou automatically. I'll be glad to write the CMakeFiles for the project.

**Comment by frno7** [comment]
@Talhada, thank you for your contribution! We’ve now moved from Make to CMake, as per https://github.com/frno7/libpes/pull/5#issuecomment-1032795503.
